[app]
address = "0.0.0.0:9000"
cors_allow_origins = "*"
cors_allow_methods = ["GET", "POST", "OPTIONS"]
cors_allow_headers = ["Content-Type", "Authorization"]

[db]
host = "exonian.clsywocmevqz.us-east-1.rds.amazonaws.com"
port = 5432
user = "postgres"
password = "password32734323"
database = "strapi"
ssl_mode = "require"
max_open = 25
max_idle = 25
max_lifetime = "300s"
params = ""
